//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWork.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryChanged
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> TypeId { get; set; }
        public Nullable<System.DateTime> DateChagned { get; set; }
        public Nullable<long> XCoordinates { get; set; }
        public Nullable<long> YCoordinates { get; set; }
    
        public virtual TypeChanged TypeChanged { get; set; }
        public virtual Users Users { get; set; }

        public string Coordination
        {
            get
            {
                return "X,Y: (" + XCoordinates + ", " + YCoordinates + ")";
            }
        }
    }
}
